# This is a basic workflow to help you get started with Actions

name: First Workflow
# Controls when the workflow will run
# by writen workflow_dispatch to run one event
#This make the that the user manually  trigger this workflow
on: workflow_dispatch 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# this must written as jobs.. not job
#remember the indentation for a new line
#Here we say that we have buch of the jobs 
jobs:
  # This workflow contains a single job called "build"
  first-job: #Here we create a frist-job with an identifier of our choice
    runs-on: ubuntu-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # name is reserved 
      - name: print Galaxy # choose a name so you can identify it
        #run key is belong to the name. 
        # Runs a set of commands using the runners shell
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Good bye!
        run: echo "Galaxy - Done!"
         
